### ISSUE TITLE
NULL value not correctly bound to parameter ?

### ISSUE THREAD

**Issue by feldti** [GemTalk/GemConnect-for-Postgres#21]
I have a table like this:

CREATE TABLE IF NOT EXISTS TIMESLOTS (EVNAME TEXT , EXITCODE INTEGER , AQMGOP BIGINT , PERIODNAME TEXT not null , DURATION INTEGER not null , IMPORTTS TIMESTAMP , SUPERID TEXT , SESSIONGOP BIGINT not null , SCREEN TEXT , WAIT TEXT , STARTTS TIMESTAMP not null , USERGOP BIGINT , ENTRYID TEXT not null PRIMARY KEY , EXTUSERID TEXT , LEVEL INTEGER not null , ROOTID TEXT , STUDY TEXT , CASENUMBER INTEGER , STUDYGOP BIGINT , CUSTOMERGOP BIGINT not null );

One can see, that some columns are nullable, some not. But, that does not matter here.

```
| writeStream conn params aCollection|
params := (GsPostgresConnectionParameters new)
		host: 'localhost';
		port: 5432;
		dbname: 'cati';
		connect_timeout: 10;
		user: 'cati';
		password: 'ByeFriends'
		yourself .
conn := GsPostgresConnection
				newWithParameters: params.
conn connect.
conn connected.

aCollection := Array new.
aCollection
	add: (CATIAPIExtDBTimeslot new 
			setPeriodName: 'Hallo' ;
			setDuration:  12;
			setSessionGop: 1;
			setStartTS: DateAndTime now;
			setLevel: 1;
			setCustomerGop: 12;
			setExitCode: 1;
			setEntryID: '1').
writeStream := conn openInsertCursorOn: CATIAPIExtDBTimeslot.
writeStream nextPutAll: aCollection.
conn commitTransaction.
```

a PostgresError occurred (error 2761), ERROR:  invalid input syntax for type bigint: "NULL"
CONTEXT:  unnamed portal parameter $3 = '...'

In the method "executePreparedStatementWithName: aName parameters: anArray", the parameter anArray looks (in my example) like:

anArray( 'NULL', '1', 'NULL', 'Hallo', '12', 'NULL', 'NULL', '1', 'NULL', 'NULL', '''2022-03-01T16:17:37.861398+00:00''', 'NULL', '1', 'NULL', '1', 'NULL', 'NULL', 'NULL', 'NULL', '12')

And I assume (!), that the array is already wrong. To bind a 'NULL' to a parameter one must bind NULL (and not the string 'NULL') to that parameter.

**Comment by feldti** [comment]
Well, I use Gemstone/S 3.6.3 and test it under Ubuntu 18.04 against PostgreSQL 14.

Here from the documentation:

paramValues[]

    Specifies the actual values of the parameters. A null pointer in this array means the corresponding parameter is null; otherwise the pointer points to a zero-terminated text string (for text format) or binary data in the format expected by the server (for binary format).

**Comment by feldti** [comment]
Ok, the test case above is too complicated - so here a bare metal table :-)

Here the table definition:

```
CREATE TABLE IF NOT EXISTS public.gemconnecttest
(
    exitcode bigint
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.gemconnecttest
    OWNER to cati;
```

Here the application code:
```
| writeStream conn params aCollection|
params := (GsPostgresConnectionParameters new)
		host: 'localhost';
		port: 5432;
		dbname: 'cati';
		connect_timeout: 10;
		user: 'cati';
		password: 'ByeFriends'
		yourself .
conn := GsPostgresConnection
				newWithParameters: params.
conn connect.
conn connected.

aCollection := Array new.
aCollection
	add: (GemConnectTest new exitcode: 3);
	add: (GemConnectTest new exitcode: nil).
writeStream := conn openInsertCursorOn: GemConnectTest.
writeStream nextPutAll: aCollection.
conn commitTransaction.
```
And here the topaz code for that class:

```
set compile_env: 0
! ------------------- Class definition for GemConnectTest
expectvalue /Class
doit
Object subclass: 'GemConnectTest'
	instVarNames: #( exitcode)
	classVars: #( Lf Tab)
	classInstVars: #()
	poolDictionaries: #()
	inDictionary: ''
	category: 'GemTest'
	options: #()

%
expectvalue /Class
doit
GemConnectTest category: 'GemTest'
%
! ------------------- Remove existing behavior from GemConnectTest
expectvalue /Metaclass3
doit
GemConnectTest removeAllMethods.
GemConnectTest class removeAllMethods.
%
set compile_env: 0
! ------------------- Class methods for GemConnectTest
category: 'other'
classmethod: GemConnectTest
rdbColumnMapping

^ Array new
	add: (GsPostgresColumnMapEntry newForColumn: 'exitcode' instVar: 'exitcode' instVarClass: SmallInteger) ;
	yourself
%
category: 'other'
classmethod: GemConnectTest
rdbTableName


^'GEMCONNECTTEST'
%
! ------------------- Instance methods for GemConnectTest
category: 'Accessing'
method: GemConnectTest
exitcode
	^exitcode
%
category: 'Updating'
method: GemConnectTest
exitcode: newValue
	exitcode := newValue
%
```

**Comment by nrgiii** [comment]
Thanks for the simple test case, it was very helpful. 
I think I have fixed this issue. 'NULL' strings in the array must be replaced with C NULLs before calling Postgres. I've adjusted the code that builds the C buffers to do this.  The test case you posted above now passes.

**Comment by feldti** [comment]
Yes, that helped ! Thanks !
