### ISSUE TITLE
Feature Request - Column, not writeable - but readable

### ISSUE THREAD

**Issue by feldti** [GemTalk/GemConnect-for-Postgres#22]
I would like to have a feature, so that a column in a database is read-only - it will never considered during writing, but it will always be considered during read operations.

Why ?

serial columns or data column, where the data is filled by the relational database.

**Comment by feldti** [comment]
I could do this by myself, but I need to define this behaviour and the rdbColumnMapping is the correct place for that. I already have written a subclass with additional column information - index creation stuff, nullable option and serial options - so it seems, that this class is a good candiate for getting bigger and bigger over time ...

**Comment by nrgiii** [comment]
I can look into that as I have time. So the column would be marked read-only in GCFP, not in Postgres itself correct? Attempting to write a column marked read-only would raise an exception.

**Comment by feldti** [comment]
Ok, consider a column id like 

CREATE TABLE table_name(
    id SERIAL,
   name text,
);

You want to have the read the values, but you are not allowed to write that column.

**Comment by nrgiii** [comment]
>You want to have the read the values, but you are not allowed to write that column.
Not writing the column would apply only to UPDATE operations right? INSERT and DELETE would still be allowed to add/remove rows when the table contains a read-only column?

**Comment by nrgiii** [comment]
I am thinking of implementing this feature by excluding columns marked read-only from update streams (#openUpdateCursorOn: tupleClass columnMapping: columnMap keyMapping: keyMap tableName: tableName). Would this meet your needs for this feature?

**Comment by nrgiii** [comment]
Add ability to mark GsPostgresColumnMapEntry objects as read-only. When this is done, updates will silently exclude any columns marked read-only. Inserts and deletes work as normal and are not affected. See class WidgetWithReadOnlyStrings and PostgresTestCase>>test_insertUpdateDeleteOnReadOnly for example usage.
