### ISSUE TITLE
Memory Leak ?

### ISSUE THREAD

**Issue by feldti** [GemTalk/GemConnect-for-Postgres#23]
I'm currently inserting around 35 million data records into a database - and I use the prepare sql statement feature of this library. More or less always the same stuff. Prepare a statement based on a table definition and then execute this statements for around 1000 instances - and this repeats around 35000 times. All high level stuff in this library.

And I notice, that there *seems* to be a memory leak - I noticed, that the memory usage goes up forever. It seems to be related to the number of prepared statements I execute.

The topaz process starts with around 317M shared memory and I killed one process at around 8800M shared memory.

I can not be more concrete right now - just a notice here. I will change my application in that way, that the PostgreSQL exporter will restart each night to reduce this problem. Of course I do not export that many data records each day - its the work of the last two years in a customer database for testing purposes.

**Comment by martinmcclure** [comment]
Is this a linked Topaz? If so, every page in the SPC that is touched by that Topaz will be reported as part of the RSS of the process. This will tend to increase as persistent objects are accessed or committed, until eventually the entire SPC size is included in the RSS.
So that's one possible explanation. 
But if your Topaz RSS is a _lot_ bigger than your SPC, that would indicate a leak.
You can use the smem utility (which may not be installed by default) to monitor memory usage. The "USS" number is the one to watch -- if that keeps increasing it's probably a memory leak.

**Comment by nrgiii** [comment]
I wrote some simple code that prepares a statement which inserts a random integer into a table. Then execute the prepared statement 1000 times.  I ran this code 100 times under valgrind and exited topaz without closing the Postgres connection. I do not see evidence of a memory leak from the valgrind output.

One possible leak is that the prepared statements do not get freed as documented here under PQprepare 
(https://www.postgresql.org/docs/11/libpq-exec.html#LIBPQ-EXEC-MAIN), but I don't know if those take any memory in client library (valgrind doesn't show any).
"Also, although there is no libpq function for deleting a prepared statement, the SQL [DEALLOCATE](https://www.postgresql.org/docs/11/sql-deallocate.html) statement can be used for that purpose."

 I'm willing to investigate further if you can come up with a test case which I can run here that demonstrates a memory leak,
As Martin said above, various parts of the SPC will be mapped into the gem's memory on demand which may make the process RSS grow. That is normal and no need for concern. However you can improve performance by enabling Linux Huge Memory Pages for large shared page caches.

**Comment by feldti** [comment]
Yes, I will take a look at that problem next week. And the problem with linked topaz processes - I use quite a lot of such processes in my application and they are long-running processes (e.g.180 days) and I never found such problems. But as I say - next week, I will take a closer look. Other than that - due to the fact, that I have to deliver our product with this library I'll terminate the application after six hours and restart it again.
