### ISSUE TITLE
Reading float from database fails ...

### ISSUE THREAD

**Issue by feldti** [GemTalk/GemConnect-for-Postgres#26]
Strange stuff, I was able to write float values into a database, but was not able to read those values from the database - instead I get a NaN. I assume also a locale error, but have to found the conversion in the code.

**Comment by feldti** [comment]
I changed to "fromStringLocaleC:" and then I could read the float values from the database

GsPostgresResult class >>createInstanceOf: aClass fromFloatString: aString
	"GsPostgresResult createInstanceOf: Float fromFloatString: '  $3,331.82'"
	"GsPostgresResult createInstanceOf: ScaledDecimal fromFloatString: '  $3,331.82'"
	"GsPostgresResult createInstanceOf: SmallDouble fromFloatString: '  $3,331.82'"
	"GsPostgresResult createInstanceOf: SmallDouble fromFloatString: '  3.1415927'"

	"This code is needed to make Postgres 'money' type map correctly to ScaledDecimal. The $$ and $, characters need to be removed"

	| rs str |
	rs := ReadStreamPortable on: aString.
	rs skipSeparators.
	rs peek == $$
		ifTrue:  "We have a currency "
			[str := String new.
			[rs atEnd] whileFalse:
					[| char |
					char := rs next.
					char isDigit
						ifTrue: [str add: char]
						ifFalse: [rs position == (rs size - 2) ifTrue: [str add: char]]]]
		ifFalse: [str := rs upToEnd]. "Not a currency, just create the class from what we have"
	^aClass fromStringLocaleC: str

**Comment by nrgiii** [comment]
I merged your fix. If you send me your DB locale settings I can runs some tests and see what else needs to change to support other locales.
