### ISSUE TITLE
Writing floats to database failed ... locale

### ISSUE THREAD

**Issue by feldti** [GemTalk/GemConnect-for-Postgres#27]
I forgot to mention this error ... its the opoosite of the read error ... creating the SQL statement with a current locale oriented method is not so good.

GsPostgresWriteStream class>>floatToPostgresString: anObj escaped: isEscaped

^ isEscaped ifTrue:[ anObj asString quoted ] ifFalse:[ anObj asStringLocaleC ]

**Comment by nrgiii** [comment]
Merged fix for issue #27
